name: SAST - Semgrep (CLI)

on:
  push:
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep (JSON output)
        run: semgrep --config=auto --json > semgrep-report.json

      # âœ… YOU CAN ADD THIS AT THE END
      - name: Generate SAST HTML report
        run: |
          python scripts/semgrep_to_html.py

      - name: Upload SAST HTML report
        uses: actions/upload-artifact@v4
        with:
          name: sast-html-report
          path: sast-report.html
